# Generated by Django 3.1.7 on 2021-03-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_production', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='Title',
        ),
    ]
